-- 29 EKIM ISSUE
-- 23 VESSEL NAMES
SELECT DISTINCT VESSEL_NAME FROM ARCHIVE_RAW_BOL (NOLOCK)
WHERE BOL_ID IN (SELECT BOL_ID
FROM PES_STG_BOL WITH (NOLOCK)
WHERE VESSEL_REF_ID = 6844)

SELECT REF.NAME,MIN(REF.ID) AS ID INTO TEMP_6844
  FROM GTCORE_MASTERDATA.DBO.REF_VESSEL REF,  
  (SELECT NAME,MAX(MODIFIED_DT) AS MAXDATE   
           FROM GTCORE_MASTERDATA.DBO.REF_VESSEL   
    WHERE NAME IN (SELECT ISNULL(SRC_VESSEL_NAME,VESSEL_NAME)  FROM PES.DBO.PES_STG_BOL (NOLOCK)  
        WHERE VESSEL_REF_ID = 6844 
              GROUP BY ISNULL(SRC_VESSEL_NAME,VESSEL_NAME))  
            AND DELETED = 'N'                    
          GROUP BY NAME)SUBQ  
WHERE SUBQ.NAME = REF.NAME   
  AND SUBQ.MAXDATE = REF.MODIFIED_DT   
GROUP BY REF.NAME  

SELECT * FROM TEMP_6844
 
-- 860 ROWS TO BE UPDATED  
SELECT SRC_VESSEL_NAME,COUNT(*) AS CNT  
FROM PES.DBO.PES_STG_BOL STG (NOLOCK) , TEMP_6844  
WHERE STG.SRC_VESSEL_NAME = TEMP_6844.NAME AND VESSEL_REF_ID = 6844 
GROUP BY SRC_VESSEL_NAME  
ORDER BY CNT DESC  

-- 767
SELECT COUNT(*) FROM PES.DBO.PES_STG_BOL (NOLOCK) WHERE VESSEL_REF_ID = 6844 
AND ISNULL(IS_DELETED,'') <> 'Y' 

BEGIN TRAN  
-- 719 RECORDS TO BE UPDATED 
UPDATE STG  
SET VESSEL_REF_ID = ID,MODIFY_DATE = GETDATE()  
--SELECT COUNT(*)
FROM PES.DBO.PES_STG_BOL STG , TEMP_6844  
WHERE STG.SRC_VESSEL_NAME = TEMP_6844.NAME AND VESSEL_REF_ID = 6844  
AND STG.RECORD_STATUS IN('CLEANSED','AUTOMATED')   
AND STG.BOL_STATUS IN('LATEMASTER', 'READY FOR RELEASE', 'READY')   
AND ISNULL(IS_DELETED,'') <> 'Y'   

COMMIT TRAN
