select top 10 * from pes.dbo.archive_raw_bol (nolock)
where vendor_code ='AMS'

select top 10 * from pes.dbo.archive_raw_bol (nolock)
where load_number  = 13291001











SELECT 
		D.VOYAGE_ID, 
        D.ACT_ARRIVAL_DT,
		D.MODIFIED_DT AS MODIFIED_DTFILTER, 
		D.VOYAGE_STATUS,ISNULL((CASE D.PORT_UNLADING_CD_MOD WHEN ' ' THEN NULL ELSE D.PORT_UNLADING_CD_MOD END),D.PORT_UNLADING_CD) as PORT_UNLADING_CD, 
		D.SCAC, 
		ISNULL((CASE D.VESSEL_NAME_MOD WHEN ' ' THEN NULL ELSE D.VESSEL_NAME_MOD END),D.VESSEL_NAME) AS NAME,
		ISNULL((CASE D.VOYAGE_NBR_MOD WHEN ' ' THEN NULL ELSE D.VOYAGE_NBR_MOD END),D.VOYAGE_NBR) AS VOYAGE_NBR,
		RTRIM(LTRIM(D.MANIFEST_NBR)) AS MANIFEST_NBR,
		CONVERT(VARCHAR(10),ISNULL((CASE D.ACT_ARRIVAL_DT_MOD WHEN ' ' THEN NULL ELSE D.ACT_ARRIVAL_DT_MOD END),D.ACT_ARRIVAL_DT),101) as ACT_ARRIVAL_DT,
		D.ACT_ARRIVAL_DT	, 
		D.EST_ARRIVAL_DT	, 
		D.EARLIEST_TAPE_DT	, 
		D.REMARKS as REMARKS,
		D.PENDING_CNT		, 
		D.SKIPPED_CNT		, 
		D.CLEANSED_CNT		, 
		D.PPMM_CNT			, 
		D.DELETED_CNT		, 
		D.TOTAL_CNT			, 
		D.LATE_BILLS_FLG	, 
		D.ACT_ARRIVAL_DT AS ACT_ARRIVAL_DT_FOR_CALC, 
		RTRIM(LTRIM(ACT_MANIFEST_NBR)) AS ACT_MANIFEST_NBR, 
		D.BATCH_ID			,
		D.VOYAGE_ID as V_ID	, 
		US_PORTNAME			, 
		CAST('O' AS CHAR(1)) AS Changed  
		FROM DQA_VOYAGE AS D WITH (NOLOCK) 
		WHERE 
		 
			( D.VOYAGE_STATUS <> 'INPROCESS' )
			AND ( D.DIR = 'I' )
--			AND ( D.ACT_ARRIVAL_DT >=  CONVERT(VARCHAR(10),@PROD_START_DT,101) )   
--			AND ( D.ACT_ARRIVAL_DT <=  CONVERT(VARCHAR(10),@PROD_END_DT, 101) )  
			AND D.VOYAGE_ID IN( SELECT D.DQA_VOYAGE_ID
				   FROM DQA_BL D (NOLOCK),BL_BL B (NOLOCK)
				  WHERE D.T_NBR = B.T_NBR
					AND D.LOAD_NBR  = 13291001)
		ORDER BY D.PORT_UNLADING_CD, D.SCAC, NAME, D.VOYAGE_NBR