-- STAGING
SELECT STND_VOYG_ID,* FROM PES_STG_BOL(NOLOCK)
WHERE REF_LOAD_NUM_ID = 13291001 

SP_HELPTEXT USP_PES_LOAD_EXCEPTION_TABLES

--STD_VOYAGE LOAD
-- 59 ROWS
SELECT AA.BOL_ID,AA.BOL_Nbr,AA.BOL_Wgt,A.Weight_Units,A.MEAS,A.MEAS_UNITS,A.OriginCity,
A.OriginState,A.OriginCountry,A.FinanceField,A.PayableField,AA.SLINE,A.Vessel_Code,AA.Vessel_Name,
AA.Voyage,AA.VDATE,AA.VDATE,A.ReceiptCountryCode,AA.FOREIGN_LOADING_PORT,
(CASE ISNULL(LTRIM(RTRIM(AA.DISCHARGE_PORT)),'') WHEN '' THEN AA.PORT_OF_DEPARTURE ELSE AA.DISCHARGE_PORT END),
A.MFEST_Quantity,A.MFEST_Units,AA.BOL_TEU,AA.BOL_LCL_FLAG,AA.BOL_CNTRZD_FLG,  
 A.Inbound_Entry_Type,AA.BOL_TRANS_MODE_CD,A.Manifest_Number,A.Load_Number,GETDATE(),AA.BOL_PUBLISH_CMD_FLG,  
 AA.BOL_PUBLISH_MAN_FLG,AA.BOL_PUBLISH_PTY_FLG,'N',A.NVOSCAC_Code,A.Master_BOL_Data,A.ImpExp,A.BATCH_ID,  
 A.ImagePath_0,AA.VESSEL_REF_ID,AA.SLINE_REF_ID,AA.PORT_DEPART_REF_ID,0,0,AA.SCAC,0,'USER5',GETDATE(),  
 'INPROCESS'   
 FROM PES.DBO.PES_STG_BOL AA WITH (NOLOCK), PES.DBO.ARCHIVE_RAW_BOL A WITH (NOLOCK)  
 WHERE AA.ref_load_num_id = 13291001 AND A.BOL_ID=AA.BOL_ID 
 AND (AA.VESSEL_REF_ID=0 OR AA.SLINE_REF_ID=0 OR AA.PORT_DEPART_REF_ID=0)  

-- CTRL_PROCESS_VOYAGE 
-- INVALID CARRIER EXCEPTION (SLINE_REF_ID = 0)
-- 100 ROWS
SELECT 'INVALID CARRIER',A.BOL_ID,A.BOL_DIRECTION,A.SCAC,1,GETDATE(),0,0, A.REF_VENDOR_CODE,'BOL','CARRIER_CODE',A.REF_LOAD_NUM_ID,0   
 FROM PES.DBO.PES_STG_BOL A WITH (NOLOCK)  
 WHERE  A.REF_LOAD_NUM_ID=13291001  
 AND A.SLINE_REF_ID=0  

-- RAW TO STAGING
-- PES_EXCEPTION_FILE_LOAD PACKAGE
-- SP NAME: PES_LOAD_DQA_EXCEPTION

-- LOAD DQA_BL TABLE
--UPDATE VOYAGE_ID IN DQA_BL FOR RECORDS MISSED OUT WITH VOYAGE ID FOR QC RULES  
UPDATE DQA_BL WITH (UPDLOCK)  
SET DQA_VOYAGE_ID=A.STND_VOYG_ID   
FROM PES.DBO.PES_STG_BOL A WITH (NOLOCK)  
WHERE REF_LOAD_NUM_ID=@LNBR and A.BOL_ID=DQA_BL.T_NBR AND DQA_BL.DQA_VOYAGE_ID IS NULL AND A.STND_VOYG_ID IS NOT NULL   

-- UPDATE RECORD_STATUS = 'PENDING' FOR EXCEPTION RECORDS IN DQA_BL

-- INSERT THE RECORDS INTO BL_BL TABLE



  


