BEGIN TRY 
UPDATE RAW_CMD SET PIECE_COUNT=PACKAGENUM 
FROM RAW_BOL WHERE VENDOR_CODE='ESCAN'
END TRY
BEGIN CATCH
END CATCH
GO
/*
--Change as per UBM when the Quantity blank from the DIS source Feed
BEGIN TRY 
UPDATE RAW_BOL SET MFEST_QUANTITY=X.PKG_NO FROM 
(SELECT BOL_ID,SUM(CAST(REPLACE(PACKAGENUM,',','') AS BIGINT))AS PKG_NO
FROM RAW_CMD GROUP BY BOL_ID) X  WHERE RAW_BOL.BOL_ID=X.BOL_ID  AND VENDOR_CODE='DIS' 
END TRY
BEGIN CATCH
END CATCH
GO
*/

-- Modified by Dhanya to update the Blank Quantity for DIS feeds
BEGIN TRY 
UPDATE RAW_CMD SET PIECE_COUNT=PACKAGENUM 
FROM RAW_BOL WHERE VENDOR_CODE='DIS'
AND LOAD_NUMBER IN (SELECT LOADNUMBER FROM PES_PROGRESS_STATUS (NOLOCK) WHERE LEFT(FILENAME,3) = 'DIS')
END TRY
BEGIN CATCH
END CATCH

-- Modified by Dhanya to update the Blank Quantity for DIS feeds
BEGIN TRY 
UPDATE RAW_BOL SET MFEST_QUANTITY=X.PKG_NO,MFEST_UNITS=X.PKG_UNIT FROM 
(SELECT BOL_ID,SUM(CAST(REPLACE(PACKAGENUM,',','') AS BIGINT))AS PKG_NO ,MAX(PACKAGEUNIT) AS PKG_UNIT
FROM RAW_CMD GROUP BY BOL_ID) X  WHERE RAW_BOL.BOL_ID=X.BOL_ID  AND VENDOR_CODE='DIS' 
AND LOAD_NUMBER IN (SELECT LOADNUMBER FROM PES_PROGRESS_STATUS (NOLOCK) WHERE LEFT(FILENAME,3) = 'DIS')
END TRY
BEGIN CATCH
END CATCH

BEGIN TRY 
UPDATE RAW_BOL SET MFEST_QUANTITY=X.PKG_NO,MFEST_UNITS=X.PKG_UNIT FROM 
(SELECT BOL_ID,SUM(CAST(REPLACE(PACKAGENUM,',','') AS BIGINT))AS PKG_NO ,MAX(PACKAGEUNIT) AS PKG_UNIT
FROM RAW_CMD GROUP BY BOL_ID) X  WHERE RAW_BOL.BOL_ID=X.BOL_ID  AND VENDOR_CODE='ESCAN' 
END TRY
BEGIN CATCH
END CATCH
GO
BEGIN TRY 
UPDATE RAW_BOL SET WEIGHT=X.WEIGHT,WEIGHT_UNITS=X.WEIGHT_UNIT FROM 
(SELECT BOL_ID,SUM(CASE ISNUMERIC(HARM_WEIGHT) WHEN 0 THEN 0 ELSE HARM_WEIGHT END)AS WEIGHT ,MAX(HARM_UNIT) AS WEIGHT_UNIT 
FROM RAW_CMD GROUP BY BOL_ID) X  WHERE RAW_BOL.BOL_ID=X.BOL_ID  AND VENDOR_CODE='ESCAN' 
END TRY
BEGIN CATCH
END CATCH
GO
BEGIN TRY 
UPDATE RAW_PTY SET NAME=A.CNAME,ADDR_1=A.CADDR1,ADDR_2=A.CADDR2,ADDR_3=A.CADDR3,ADDR_4=A.CADDR4
FROM
(
SELECT BOL_ID,NAME CNAME ,ADDR_1 CADDR1,ADDR_2 CADDR2,ADDR_3 CADDR3,ADDR_4 CADDR4 FROM RAW_PTY WHERE SOURCE='C' AND BOL_ID IN(
SELECT BOL_ID FROM RAW_PTY WHERE NAME  LIKE '%SAME AS CONSIGNEE' AND SOURCE='N'))A
WHERE RAW_PTY.BOL_ID=A.BOL_ID AND SOURCE='N'
END TRY
BEGIN CATCH
END CATCH

GO
EXEC  dbo.PES_RAW_SOFTERR

GO

--Change as per UBM when Shipper Information comes Blank from the source for Export Feed 

UPDATE RAW_PTY WITH (UPDLOCK) SET NAME='ORDER OF SHIPPER' WHERE
LTRIM(RTRIM(ISNULL(NAME,'')))='' AND LTRIM(RTRIM(ISNULL(ADDR_1,'')))=''
AND BOL_ID IN(SELECT BOL_ID FROM RAW_BOL   WITH (NOLOCK)   WHERE IMPEXP='E')


GO

--Change as per UBM' instructions
UPDATE A WITH (UPDLOCK) SET 
A.NAME=B.NAME,A.ADDR_1=B.ADDR_1,A.ADDR_2=B.ADDR_2,A.ADDR_3=B.ADDR_3,A.ADDR_4=B.ADDR_4
FROM RAW_PTY A JOIN RAW_PTY B   WITH (NOLOCK)   ON A.BOL_ID=B.BOL_ID
WHERE A.SOURCE='N' AND B.SOURCE='C' AND REPLACE(A.NAME,' ','') LIKE '%ASCONSIGNEE%'

GO

UPDATE A WITH (UPDLOCK) SET 
A.NAME=B.NAME,A.ADDR_1=B.ADDR_1,A.ADDR_2=B.ADDR_2,A.ADDR_3=B.ADDR_3,A.ADDR_4=B.ADDR_4
FROM RAW_PTY A JOIN RAW_PTY B   WITH (NOLOCK)   ON A.BOL_ID=B.BOL_ID
WHERE A.SOURCE='A' AND B.SOURCE='C' AND REPLACE(A.NAME,' ','') LIKE '%ASCONSIGNEE%'


