
-- GET COMPANIES WITHOUT DUN NUMBERS
SELECT  COMP_ID,
		IS_USCOMP,
		COMPANY_NBR,
		NAME,
        DBO.PES_UDF_REMOVE_SPECIAL_CHARACTERS(NAME) AS COMPRESSEDCOMPANYNAMES,
		COMPRESSED_NAME,
		DUNS_NUMBER,
		NBR_SHIPMENTS,
		ADDRESS1,
		DBO.PES_UDF_REMOVE_SPECIAL_CHARACTERS(ADDRESS1) AS COMPRESSEDADDRESS,
		CITY,
		STATE, 
		ZIPCODE,
		COUNTY,
		COUNTRY_CD,
		PHONE   
 INTO WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS  
 FROM PESDW.DBO.PES_DW_REF_COMPANY (NOLOCK)  
WHERE DUNS_NUMBER IS NULL

-- REF DATA WITHOUT DUNS
SELECT TOP 100 * FROM WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS (NOLOCK)


SELECT REF.*
FROM WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS REF (NOLOCK) ,WORKTEMP.DBO.COMPRESSEDCOMPANY_ACCOUNTS ACCT (NOLOCK)
WHERE REF.COMPRESSEDCOMPANYNAMES = ACCT.COMPRESSEDCOMPANYNAMES

-- UPDATE COMPANY IDS AND COMPANY NUMBERS IN COMPANY ACCOUNTS TABLE
UPDATE ACCT SET COMPANYID = REF.COMP_ID,ACCT.COMPANY_NBR = REF.COMPANY_NBR
FROM WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS REF ,WORKTEMP.DBO.COMPRESSEDCOMPANY_ACCOUNTS ACCT 
WHERE REF.COMPRESSEDCOMPANYNAMES = ACCT.COMPRESSEDCOMPANYNAMES
  AND ACCT.COMPANYID IS NULL 

-- UPDATE COMPANY IDS AND COMPANY NUMBERS IN COMPANY ADDRESS ACCOUNTS TABLE
UPDATE ACCT SET COMPANYID = REF.COMP_ID,ACCT.COMPANY_NBR = REF.COMPANY_NBR
FROM WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS REF (NOLOCK) ,WORKTEMP.DBO.COMPRESSEDADDRESS_ACCOUNTS ACCT (NOLOCK)
WHERE REF.COMPRESSEDCOMPANYNAMES = DBO.PES_UDF_REMOVE_SPECIAL_CHARACTERS(ACCT.COMPANYNAME)
  AND REF.COMPRESSEDADDRESS = ACCT.COMPRESSEDADDRESS
  AND ACCT.COMPANYID IS NULL 

-- GET THE UNION OF THIS DATA
SELECT * INTO WORKTEMP.DBO.COMPANYLIST FROM 
(SELECT COMPANYID,COMPANYNAME,COMPANY_NBR FROM WORKTEMP.DBO.COMPRESSEDCOMPANY_ACCOUNTS (NOLOCK) WHERE COMPANYID IS NOT NULL
UNION
SELECT COMPANYID,COMPANYNAME,COMPANY_NBR FROM WORKTEMP.DBO.COMPRESSEDADDRESS_ACCOUNTS (NOLOCK) WHERE COMPANYID IS NOT NULL) TMP

SELECT * FROM WORKTEMP.DBO.COMPANYLIST

-- GET THE TRANSACTION COUNT
SELECT COMPANYNAME,
       COMPANYID,
       COUNT(BOL_ID) AS TRANSACTIONCNT
FROM PES_DW_BOL  DWBOL (NOLOCK),WORKTEMP.DBO.COMPANYLIST CACCT (NOLOCK)
WHERE (DWBOL.SHIPPER_COMP_REF_ID = CACCT.COMPANYID)
GROUP BY COMPANYNAME,COMPANYID
ORDER BY COUNT(BOL_ID) DESC

-- FOR THE SALES FORCE LEADS EXCEL
SELECT * FROM WORKTEMP.DBO.COMPRESSEDLEADS  (NOLOCK)
WHERE COMPANYID IS NULL

SELECT TOP 100 *  FROM WORKTEMP.DBO.COMPRESSEDLEADS (NOLOCK) WHERE COMPANY_NBR !=''
SELECT TOP 100 *  FROM WORKTEMP.DBO.COMPRESSEDADDRESSLEADS (NOLOCK) WHERE COMPANY_NBR !=''

-- UPDATE THE COMPRESSEDLEADS TABLE
UPDATE ACCT SET COMPANYID = REF.COMP_ID,ACCT.COMPANY_NBR = REF.COMPANY_NBR
FROM WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS REF (NOLOCK) ,WORKTEMP.DBO.COMPRESSEDLEADS ACCT (NOLOCK)
WHERE REF.COMPRESSEDCOMPANYNAMES = ACCT.COMPRESSEDCOMPANYNAMES
  AND ACCT.COMPANYID IS NULL 

-- UPDATE THE COMPRESSEDADDRESSLEADS TABLE
UPDATE ACCT SET COMPANYID = REF.COMP_ID,ACCT.COMPANY_NBR = REF.COMPANY_NBR
FROM WORKTEMP.DBO.COMPRESSEDREFCOMPANIESWITHOUTDUNS REF (NOLOCK) ,WORKTEMP.DBO.COMPRESSEDADDRESSLEADS ACCT (NOLOCK)
WHERE REF.COMPRESSEDCOMPANYNAMES = ACCT.COMPRESSEDCOMPANYNAMES
  AND REF.COMPRESSEDADDRESS = ACCT.COMPRESSEDSTREET
  AND ACCT.COMPANYID IS NULL 

-- GET THE UNION OF THESE DATA
SELECT * INTO WORKTEMP.DBO.COMPANYLEADS FROM 
(SELECT COMPANYID,COMPANY_ACCOUNT,COMPANY_NBR FROM WORKTEMP.DBO.COMPRESSEDLEADS (NOLOCK) WHERE COMPANYID IS NOT NULL
UNION
SELECT COMPANYID,COMPANY_ACCOUNT,COMPANY_NBR FROM WORKTEMP.DBO.COMPRESSEDADDRESSLEADS (NOLOCK) WHERE COMPANYID IS NOT NULL) TMP


SELECT * FROM  WORKTEMP.DBO.COMPANYLEADS (NOLOCK)

-- GET THE TRANSACTION COUNTS

SELECT COMPANY_ACCOUNT,
       COMPANYID,
       COUNT(BOL_ID) AS TRANSACTIONCNT
FROM PES_DW_BOL  DWBOL (NOLOCK),WORKTEMP.DBO.COMPANYLEADS CACCT (NOLOCK)
WHERE (DWBOL.SHIPPER_COMP_REF_ID = CACCT.COMPANYID)
GROUP BY COMPANY_ACCOUNT,COMPANYID
ORDER BY COUNT(BOL_ID) DESC












