-- CHECK IF THE DAHNAY BILLS ARE UPDATED ON STAGING
-- COUNT = 2789 ROWS
SELECT top 10 nvo_scac,* 
--INTO TEMP_PES.DBO.DLPD_UPDATE_NEW 
FROM PES.DBO.PES_STG_BOL STG(NOLOCK)
WHERE ISNULL(IS_DELETED,'') <> 'Y'
AND STG.RECORD_STATUS IN('CLEANSED','AUTOMATED') 
AND STG.BOL_STATUS IN('LATEMASTER', 'READY FOR RELEASE', 'READY')
and isnull(nvo_scac,'') <> ''

begin tran
UPDATE PES_STG_BOL SET MODIFY_DATE = GETDATE(),MODIFY_USER = 'DATA_DEV'
WHERE BOL_ID IN (SELECT BOL_ID FROM TEMP_PES.DBO.DLPD_UPDATE_NEW)
select modify_user,modify_date,* from pes_stg_bol (nolock) 
WHERE BOL_ID IN (SELECT BOL_ID FROM TEMP_PES.DBO.DLPD_UPDATE_NEW)
commit tran

SELECT BOL_ID, MODIFY_DATE 
FROM PES_STG_BOL A with (nolock)
JOIN PES_PROCESS_DATE B WITH (nolock) 
ON A.MODIFY_DATE>= DateADD(hh, -12, B.LAST_UPD_DATE) --If job past midnight Savvis time, the last updated_date -- changes to next date
WHERE
-- Added by Dhanya to block the load nbrs 02Aug2012  
 A.RECORD_STATUS IN('CLEANSED','AUTOMATED') 
AND A.BOL_STATUS 
IN( 'LATEMASTER', 'READY FOR RELEASE', 'READY') 
AND ISNULL(IS_DELETED,'') <> 'Y' 
AND B.PROCESS_NAME='STG_DW'
AND A.BOL_ID IN (SELECT BOL_ID FROM TEMP_PES.DBO.DLPD_UPDATE_NEW)





 
