ALTER PROCEDURE PES_REMOVE_DUPLICATES 
( 
	@YEAR VARCHAR(20) = '2012',
	@MONTH VARCHAR(20) = '04,05,06,07',
	@DIS_VENDOR_CODE VARCHAR(20) = 'DIS',
    @OTHER_VENDOR_CODE VARCHAR(20) = 'ESCAN'
)
AS

SET @MONTH =  REPLACE(@MONTH,',',''',''') 

DECLARE @SQL NVARCHAR(500)
DECLARE @SQL2 NVARCHAR(500)
DECLARE @SQL3 NVARCHAR(500)

-- FIND THE DUPLICATE BILL NUMBERS FROM DIS AND OTHER FEEDS
SET @SQL2 = 'SELECT D.BOL_ID, D.BOL_NUMBER,DISCHARGE_PORT, PORT_OF_DESTINATION, VOYAGE_NUMBER, D.SAILING_DATE INTO DIS_DUPLICATES FROM PES.DBO.ARCHIVE_RAW_BOL D (NOLOCK)  WHERE D.VENDOR_CODE= ''' +@DIS_VENDOR_CODE+ ''' AND SUBSTRING(D.SAILING_DATE,1,2) IN (''' +@MONTH+ ''') AND SUBSTRING(D.SAILING_DATE,5,4)=''' +@YEAR+ ''''
EXEC (@SQL2)

SET @SQL3 = 'SELECT  D.BOL_ID, D.BOL_NUMBER,DISCHARGE_PORT, PORT_OF_DESTINATION, VOYAGE_NUMBER, D.SAILING_DATE INTO ESCAN_DUPLICATES FROM PES.DBO.ARCHIVE_RAW_BOL D (NOLOCK)  WHERE D.VENDOR_CODE=  ''' +@OTHER_VENDOR_CODE+ ''' AND SUBSTRING(D.SAILING_DATE,1,2) IN (''' +@MONTH+ ''') AND SUBSTRING(D.SAILING_DATE,5,4)=''' +@YEAR+ ''''
EXEC (@SQL3)

INSERT INTO TEMP_PES.DBO.DISESCAN_DUPLICATES
SELECT E.BOL_ID, E.BOL_NUMBER,E.DISCHARGE_PORT, E.PORT_OF_DESTINATION, E.VOYAGE_NUMBER, E.SAILING_DATE,
	   D.BOL_ID DIS_BOL_ID, D.BOL_NUMBER DIS_BILL_NUMBER,D.DISCHARGE_PORT DIS_DISCHARGEPORT, 
       D.PORT_OF_DESTINATION DIS_PORTOFDESTINATION, D.VOYAGE_NUMBER DIS_VOYAGENUMBER, D.SAILING_DATE DIS_SAILINGDATE
FROM DIS_DUPLICATES D JOIN ESCAN_DUPLICATES E ON 
(D.BOL_NUMBER=E.BOL_NUMBER 
AND D.DISCHARGE_PORT=E.DISCHARGE_PORT 
AND D.PORT_OF_DESTINATION=E.PORT_OF_DESTINATION
--AND D.VOYAGE_NUMBER=E.VOYAGE_NUMBER
AND D.SAILING_DATE=E.SAILING_DATE)

-- 2919 ROWS
SELECT * FROM TEMP_PES.DBO.DISESCAN_DUPLICATES (NOLOCK)

EXEC PES_REMOVE_DUPLICATES

/* DELETE DIS RECORDS - UPDATING THE STG BOL TABLE FOR THE DUPLICATE DIS ESCAN BOL_NUMBERS*/ 

-- DIS COUNT = 2551

--UPDATE  STG
--SET  STG.IS_DELETED='Y',MODIFY_DATE=GETDATE()
SELECT * 
FROM PES.DBO.PES_STG_BOL  STG   WHERE STG.BOL_ID IN 
(SELECT DIS_BOL_ID FROM TEMP_PES.DBO.DISESCAN_DUPLICATES  WITH (NOLOCK))
--AND STG.REF_VENDOR_CODE=@DIS_VENDOR_CODE
AND STG.REF_VENDOR_CODE='DIS'

/* UPDATING THE STG CMD TABLE FOR THE DUPLICATE DIS ESCAN BOL_NUMBERS*/ 

--DISCOUNT  = 122

--UPDATE  STGCMD
--SET  STGCMD.IS_DELETE='Y',MODIFY_DATE=GETDATE()
SELECT * 
FROM PES.DBO.PES_STG_CMD STGCMD WHERE STGCMD.BOL_ID IN 
(SELECT DIS_BOL_ID FROM TEMP_PES.DBO.DISESCAN_DUPLICATES  WITH (NOLOCK))

/* UPDATING THE DW BOL TABLE FOR THE DUPLICATE DIS ESCAN BOL_NUMBERS*/

-- DISCOUNT = 2527
 
--UPDATE  DW
--SET DW.MODIFY_DATE=GETDATE(), DW.DELETED='Y'
--SELECT COUNT(*)
FROM PES_DW.PESDW.DBO.PES_DW_BOL  DW  WHERE DW.BOL_ID IN 
(SELECT DIS_BOL_ID FROM TEMP_PES.DBO.DISESCAN_DUPLICATES  WITH (NOLOCK))
AND DW.VENDOR_CODE='DIS'

/* UPDATING THE DW CMD TABLE FOR THE DUPLICATE DIS ESCAN BOL_NUMBERS*/
-- DIS COUNT = 4108

--UPDATE  DWCMD
--SET DWCMD.MODIFY_DATE=GETDATE(), DWCMD.DELETED='Y'
SELECT DWCMD.*
FROM PES_DW.PESDW.DBO.PES_DW_CMD  DWCMD (NOLOCK) WHERE DWCMD.BOL_ID IN 
(SELECT DIS_BOL_ID FROM TEMP_PES.DBO.DISESCAN_DUPLICATES  WITH (NOLOCK))

/* INSERTING ALL THE ONLY DIS DUPLICATE DATA INTO THE PHYSICAL TABLE */
DECLARE @SQL NVARCHAR(500)
DECLARE @MONTH NVARCHAR(10)
SET @MONTH = '04'

SET @MONTH =  REPLACE(@MONTH,',',''',''') 
--SET @SQL = 'INSERT INTO TEMP_PES.DBO.DISESCAN_DUPLICATES SELECT D.BOL_ID, D.BOL_NUMBER,DISCHARGE_PORT, PORT_OF_DESTINATION, VOYAGE_NUMBER, D.SAILING_DATE FROM PES.DBO.ARCHIVE_RAW_BOL D (NOLOCK)  WHERE D.VENDOR_CODE= ''' +@DIS_VENDOR_CODE+ ''' AND SUBSTRING(D.SAILING_DATE,1,2) IN (''' +@MONTH+ ''') AND SUBSTRING(D.SAILING_DATE,5,4)=''' +@YEAR+ ''''
SET @SQL = 'INSERT INTO TEMP_PES.DBO.ONLYDIS_DUPLICATES SELECT D.BOL_ID, D.BOL_NUMBER,DISCHARGE_PORT, PORT_OF_DESTINATION, VOYAGE_NUMBER, D.SAILING_DATE FROM PES.DBO.ARCHIVE_RAW_BOL D (NOLOCK)  WHERE D.VENDOR_CODE= ''DIS'' AND SUBSTRING(D.SAILING_DATE,1,2) IN (''' +@MONTH+ ''') AND SUBSTRING(D.SAILING_DATE,5,4)=''2012'''
EXEC (@SQL)

/* PULLING ALL THE DUPLICATE BOL_NBR FROM THE PHYSICAL TABLE WHAT HAS THE DUPLICATE DIS RECORDS */
;WITH CTE 
AS
(
SELECT	BOL_NUMBER,BOL_ID ,ROW_NUMBER() OVER (PARTITION BY BOL_NUMBER ORDER BY BOL_NUMBER ) AS ROWID
	FROM TEMP_PES.DBO.ONLYDIS_DUPLICATES
),
TMPA 
AS 
(
SELECT * FROM  CTE 
WHERE ROWID>1
)
SELECT * FROM TMPA 
--SELECT * INTO #TEMP FROM TMPA 

-- 9428 DUPLICATE ROWS
--SELECT COUNT(*) FROM #TEMP


/* DELETE DUPLICATES FROM STG BOL TABLE FOR THE DUPLICATE DIS BOL_NUMBERS*/
--UPDATE  STG
--SET  STG.IS_DELETED='Y',MODIFY_DATE=GETDATE()
SELECT COUNT(*)
FROM PES.DBO.PES_STG_BOL  STG   WHERE STG.BOL_ID IN 
--(SELECT BOL_ID FROM TMPA  WITH (NOLOCK))
(SELECT BOL_ID FROM #TEMP  WITH (NOLOCK))
AND STG.REF_VENDOR_CODE='DIS'

/* DELETE DUPLICATES FROM STG CMD TABLE FOR THE DUPLICATE DIS BOL_NUMBERS*/
--UPDATE  STGCMD
--SET  STGCMD.IS_DELETE='Y',MODIFY_DATE=GETDATE()
SELECT COUNT(*)
FROM PES.DBO.PES_STG_CMD  STGCMD   WHERE STGCMD.BOL_ID IN 
--(SELECT BOL_ID FROM TMPA  WITH (NOLOCK))
(SELECT BOL_ID FROM #TEMP  WITH (NOLOCK))

-- 8955 ROWS
/* UPDATING THE DW BOL TABLE FOR THE DUPLICATE DIS BOL_NUMBERS*/
--UPDATE  DW
--SET DW.MODIFY_DATE=GETDATE(), DW.DELETED='Y'
SELECT COUNT(*)
FROM PES_DW.PESDW.DBO.PES_DW_BOL  DW  WHERE DW.BOL_ID IN 
--(SELECT BOL_ID FROM TMPA  WITH (NOLOCK))
(SELECT BOL_ID FROM #TEMP  WITH (NOLOCK))
--AND DW.VENDOR_CODE='DIS'

/* UPDATING THE DW CMD TABLE FOR THE DUPLICATE DIS BOL_NUMBERS*/

--6276 ROWS
--UPDATE  DWCMD
--SET DWCMD.MODIFY_DATE=GETDATE(), DWCMD.DELETED='Y'
--SELECT DISTINCT TOP 10  DELETED  
SELECT DWCMD.*
FROM PES_DW.PESDW.DBO.PES_DW_CMD  DWCMD (NOLOCK) WHERE DWCMD.BOL_ID IN 
--(SELECT BOL_ID FROM TMPA  WITH (NOLOCK))
(SELECT BOL_ID FROM #TEMP  WITH (NOLOCK))
--AND DW.VENDOR_CODE='DIS'

DROP TABLE DIS_DUPLICATES
DROP TABLE ESCAN_DUPLICATES
DELETE TEMP_PES.DBO.DISESCAN_DUPLICATES 





