-- REGISTRY EXCEPTIONS

SELECT MONTH(MODIFIED_DT),COUNT(*) FROM SCREEN_TEST.DBO.CTRL_PROCESS_VOYAGE (NOLOCK)
WHERE PROCESS_NAME = 'INVALID REGISTRY' AND YEAR(MODIFIED_DT) = '2012'
GROUP BY MONTH(MODIFIED_DT)
ORDER BY MONTH(MODIFIED_DT)

SELECT COUNT(*) FROM PES.DBO.PES_STG_BOL (NOLOCK)
WHERE REGISTRY_ID = 0
AND ISNULL(IS_DELETED,'') <> 'Y'

-- GET ALL EXCEPTION RECORDS FROM STAGING

SELECT * INTO #REG_EXCPS
FROM PES_STG_BOL STG (NOLOCK)
WHERE STG.REGISTRY_ID = 0

-- FIND THE COUNTRY FOR THESE VESSELS FROM REF_VESSEL TABLE
SELECT STG.BOL_ID,REF.VESSEL_COUNTRY 
--INTO #TMP_UPD
FROM PES_STG_BOL STG,REF_VESSEL REF(NOLOCK)
WHERE STG.VESSEL_NAME = REF.NAME
AND STG.REGISTRY_ID = 0


SELECT REF.COUNTRY_ID,UPD.* INTO #TMP_UPDATE1
FROM #TMP_UPD UPD,REF_COUNTRY REF
WHERE UPD.VESSEL_COUNTRY = COUNTRY


select * from #TMP_UPDATE1

-- UPDATE STG SET REGISTRY_ID = UPD1.COUNTRY_ID,MODIFY_DATE = GETDATE(),MODIFY_USER = 'DATA_DEV'
FROM PES_STG_BOL STG,#TMP_UPDATE1 UPD1
SET STG.REGISTRY_ID = COUNTRY_ID
WHERE STG.BOL_ID = UPD1.BOL_ID

SELECT * FROM REF_VESSEL (NOLOCK) WHERE VESSEL_COUNTRY  = 'ZZZZ' AND DELETED = 'N'

