-- FIND REGISTRY EXCEPTIONS
SELECT TOP 100 * FROM SCREEN_TEST.DBO.CTRL_PROCESS_VOYAGE (NOLOCK)
WHERE PROCESS_NAME LIKE '%INVALID REGISTRY%' AND MODIFIED_DT IS NOT NULL
ORDER BY MODIFIED_DT

--- EXAMPLES - BOL_ID = 104567767,104568160,104941982

SELECT * FROM PES_STG_BOL (NOLOCK) WHERE BOL_ID IN 
(SELECT TOP 100 T_NBR FROM SCREEN_TEST.DBO.CTRL_PROCESS_VOYAGE (NOLOCK)
WHERE PROCESS_NAME LIKE '%INVALID REGISTRY%' )

SELECT * FROM ARCHIVE_RAW_BOL (NOLOCK)
WHERE BOL_ID IN 
(SELECT TOP 100 T_NBR FROM SCREEN_TEST.DBO.CTRL_PROCESS_VOYAGE (NOLOCK)
WHERE PROCESS_NAME LIKE '%INVALID REGISTRY%')

-- CHECK IF THE VESSEL IS REGISTERED

SELECT DIR, VESSEL, CODE, REGISTRY
FROM PES_REGISTRY_RULES
JOIN REF_CARRIER
ON SLINE = TYPE
WHERE DELETED = 'N' AND VESSEL LIKE '%EL YUNQUE%'

SELECT * FROM REF_COUNTRY WHERE [ISO ALPHA-2 CODE] IS NOT NULL

SELECT * FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE STND_VESSEL = 'EL YUNQUE'

-- REGSITRY LOOK UP
-- MATCH VESSEL_COUNTRY AND PIERS_COUNTRY
-- O/P: COUNTRY_ID

SELECT DISTINCT PIERS_COUNTRY,COUNTRY,COUNTRY_ID FROM REF_COUNTRY (NOLOCK) WHERE PIERS_COUNTRY IS NOT NULL
--AND PIERS_COUNTRY = 'UNITED KINGDOM'
ORDER BY PIERS_COUNTRY DESC

-- FIND THE LIST OF DISTINCT COUNTRY NAMES FROM RAW TABLE
SELECT DISTINCT VESSEL_COUNTRY INTO #TMPVSLCNTRY FROM ARCHIVE_RAW_BOL (NOLOCK)
ORDER BY VESSEL_COUNTRY

-- 140 MATCHING COUNTRIES
SELECT * 
FROM #TMPVSLCNTRY,REF_COUNTRY
WHERE PIERS_COUNTRY = VESSEL_COUNTRY

-- 81 MATCHING COUNTRIES
SELECT * 
FROM #TMPVSLCNTRY,REF_COUNTRY
WHERE COUNTRY = VESSEL_COUNTRY

-- 15462
SELECT * FROM REF_VESSEL (NOLOCK) WHERE ISNULL(VESSEL_COUNTRY,'') <> '' 


SELECT * FROM REF_COUNTRY (NOLOCK)










