-- 846 ROWS
SELECT COUNT(*) FROM PES_STG_BOL (NOLOCK)
WHERE REF_LOAD_NUM_ID = 12299007
AND ISNULL(IS_DELETED,'') <> 'Y'  

BEGIN TRAN  
  
/* DELETE RECORDS FROM STG BOL TABLE FOR LOAD NUMBER = 12299007*/  
UPDATE  STG  
SET  STG.IS_DELETED='Y',MODIFY_DATE=GETDATE()  
--SELECT COUNT(*)  
FROM PES.DBO.PES_STG_BOL STG WHERE  
REF_LOAD_NUM_ID = 12299007
AND ISNULL(STG.IS_DELETED,'') <> 'Y'  
  
/* DELETE RECORDS FROM STG CMD TABLE FOR LOAD NUMBER = 12299007*/   
UPDATE  STGCMD  
SET  STGCMD.IS_DELETE='Y',MODIFY_DATE=GETDATE()  
--SELECT COUNT(*)  
FROM PES.DBO.PES_STG_CMD STGCMD WHERE STGCMD.BOL_ID IN   
(SELECT BOL_ID FROM PES.DBO.PES_STG_BOL STG (NOLOCK) WHERE REF_LOAD_NUM_ID = 12299007)
AND ISNULL(STGCMD.IS_DELETE,'') <> 'Y'  

COMMIT TRAN