--842
SELECT COUNT(*) FROM PESDW.DBO.PES_DW_BOL (NOLOCK)
WHERE LOAD_NUMBER = 12299007

BEGIN TRAN

/* DELETE RECORDS FROM DW BOL TABLE FOR LOAD NUMBER = 12299007*/  
 
UPDATE  DW
SET DW.MODIFY_DATE=GETDATE(), DW.DELETED='Y'
--SELECT COUNT(*)
FROM PESDW.DBO.PES_DW_BOL  DW  WHERE LOAD_NUMBER = 12299007
AND ISNULL(DW.DELETED,'') <> 'Y'

/* DELETE RECORDS FROM DW CMD TABLE FOR LOAD NUMBER = 12299007*/  
-- 1472
UPDATE  DWCMD
SET DWCMD.MODIFY_DATE=GETDATE(), DWCMD.DELETED='Y'
--SELECT DWCMD.*
FROM PESDW.DBO.PES_DW_CMD  DWCMD (NOLOCK) WHERE DWCMD.BOL_ID IN 
(SELECT BOL_ID FROM PESDW.DBO.PES_DW_BOL (NOLOCK) WHERE LOAD_NUMBER = 12299007)
AND ISNULL(DWCMD.DELETED,'') <> 'Y'

COMMIT TRAN