-- DIS DATA 
-- BOL COUNT,TEU SUM

SELECT MONTH(DIS_VDATE) AS MONTH,COUNT(DIS_BOL_ID) AS DIS_CNT,SUM(BOL_TEU) AS TEU_SUM
FROM TEMP_PES.DBO.DISESCAN_DUPLICATES1 DUP (NOLOCK),PES_STG_BOL STG (NOLOCK) 
WHERE DUP.DIS_BOL_ID = STG.BOL_ID
GROUP BY MONTH(DIS_VDATE)
ORDER BY MONTH(DIS_VDATE)

SELECT MONTH(DUP.VDATE) AS MONTH,COUNT(DUP.BOL_ID) AS OTHER_DUP_CNT,SUM(BOL_TEU) AS TEU_SUM
FROM TEMP_PES.DBO.DISESCAN_DUPLICATES1 DUP (NOLOCK),PES_STG_BOL STG (NOLOCK) 
WHERE DUP.BOL_ID = STG.BOL_ID
GROUP BY MONTH(DUP.VDATE)
ORDER BY MONTH(DUP.VDATE)

SELECT RAW.SAILING_DATE,DUP.*
FROM TEMP_PES.DBO.DISESCAN_DUPLICATES1 DUP (NOLOCK),ARCHIVE_RAW_BOL (NOLOCK) RAW
WHERE DUP.BOL_ID =  RAW.BOL_ID
AND MONTH(DUP.VDATE) = 10
ORDER BY DUP.BOL_ID

SELECT SUBSTRING(DUP.SAILING_DATE,1,2) AS MONTH,COUNT(DUP.DIS_BOL_ID) AS DIS_DUP_CNT,SUM(BOL_TEU) AS TEU_SUM
FROM TEMP_PES.DBO.DISESCAN_DUPLICATES DUP,PES_STG_BOL STG (NOLOCK)
WHERE DUP.DIS_BOL_ID = STG.BOL_ID
AND ISNULL(STG.IS_DELETED,'') <> 'Y'
GROUP BY  SUBSTRING(DUP.SAILING_DATE,1,2)
ORDER BY  SUBSTRING(DUP.SAILING_DATE,1,2)


SELECT * 
FROM TEMP_PES.DBO.DISESCAN_DUPLICATES DUP,PES_STG_BOL STG
WHERE DUP.DIS_BOL_ID = STG.BOL_ID
AND SUBSTRING(SAILING_DATE,1,2) = '09'





SELECT IS_DELETED, * FROM PES_STG_BOL (NOLOCK)
WHERE BOL_ID = 260956787

SELECT * FROM PES_STG_BOL (NOLOCK)
WHERE BOL_NBR = 'MSCUOE678427' 

--
--UPDATE  STG  
--SET  STG.IS_DELETED='Y',MODIFY_DATE=GETDATE()  
SELECT *
FROM PES.DBO.PES_STG_BOL STG WHERE STG.BOL_ID IN   
(SELECT DIS_BOL_ID FROM TEMP_PES.DBO.DISESCAN_DUPLICATES  WITH (NOLOCK))  
AND STG.REF_VENDOR_CODE= 'DIS'  
AND ISNULL(STG.IS_DELETED,'') <> 'Y'  
AND STG.BOL_ID IN
(
259760595,
259760596,
259760597,
259760598,
259760599,
259760600
)

select is_deleted,* from pes_stg_bol (nolock)
where bol_id in
(
259760595,
259760596,
259760597,
259760598,
259760599,
259760600
)


