	SELECT count(*)--BOL_ID
	 FROM PES.dbo.PES_STG_BOL A WITH (NOLOCK)
	JOIN PES.dbo.PES_PROGRESS_STATUS B WITH (NOLOCK)
	ON A.REF_LOAD_NUM_ID=B.LOADNUMBER
	WHERE A.RECORD_STATUS IN ('CLEANSED','AUTOMATED') AND A.PPMM_FLAG='Y'
	AND B.LOAD_DT <= GETDATE() - 30 --92
	and B.LOAD_DT >= '2012-01-01'
	-- reccount 31538098
	--          40261889
	UNION 
	SELECT count(*)--BOL_ID
	 FROM PES.dbo.PES_STG_BOL A WITH (NOLOCK)
	JOIN PES.dbo.PES_PROGRESS_STATUS B WITH (NOLOCK)
	ON A.REF_LOAD_NUM_ID=B.LOADNUMBER
	WHERE A.BOL_STATUS in ('MASTER', 'HOUSE') 
	AND B.LOAD_DT <= GETDATE() - 30 --92
	and B.LOAD_DT >= '2012-01-01'

select count(*) from PES_PURGE.dbo.TEMP_BOLID

select loadnumber,load_dt from PES.dbo.PES_PROGRESS_STATUS
where LOAD_DT >= '2012-01-01'  and LOAD_DT<=GETDATE() - 30