
-- Reference Data
SELECT  UN.COUNTRY + UN.LOCATION AS 'UNLOCODE', 
		UN.NAME, UN.NAMEWODIACRITICS, PORT.ID, COUNTRY.PIERS_COUNTRY
INTO TEMP_PES.DBO.PORT_REF_UPDATE
FROM GTCORE_MASTERDATA.DBO.REF_UNLOCODE_UNLOCODES UN WITH (NOLOCK)
JOIN GTCORE_MASTERDATA.DBO.REF_PORT PORT WITH (NOLOCK) ON UN.NAME = PORT.PORT_NAME
JOIN GTCORE_MASTERDATA.DBO.REF_COUNTRY COUNTRY WITH (NOLOCK) 
	ON SUBSTRING(PORT.CODE, 1, 3) = COUNTRY.JOC_CODE
WHERE COUNTRY.[ISO ALPHA-2 CODE] = UN.COUNTRY


SELECT * FROM TEMP_PES.DBO.PORT_REF_UPDATE REF (NOLOCK) 

-- Look up reference data
SELECT  *
FROM TEMP_PES.DBO.PORT_REF_UPDATE REF (NOLOCK)
WHERE ID NOT IN (SELECT ID FROM PES_REF_FOREIGN_PORT_FUZZY FUZZY (NOLOCK) )




