SELECT * FROM PES_PORT_CONVERSION WHERE IS_US_PORT='1'

-- discharge port look up
SELECT * FROM REF_PORT 
WHERE IS_US_PORT=1 AND IS_TMP='N' AND DELETED='N'
 AND CODE IN(SELECT CODE FROM REF_PORT WHERE IS_US_PORT=1 AND IS_TMP='N' 
				AND DELETED='N' GROUP BY CODE HAVING COUNT(*)=1)

-- us port look up
SELECT A.NAME_KEY,A.REF_ID FROM LIB_PORT A, REF_PORT B WHERE A.REF_ID=B.ID AND A.IS_US_PORT=1 
AND B.IS_US_PORT=1 AND B.DELETED='N' AND B.IS_TMP='N' 
AND A.NAME_KEY IN(SELECT NAME_KEY FROM LIB_PORT WHERE IS_US_PORT=1 GROUP BY NAME_KEY HAVING COUNT(*)=1)


SELECT SOURCE,TARGET FROM 
PES_PORT_CONVERSION 
WHERE IS_US_PORT=0

-- ref port look up
SELECT * FROM REF_PORT WHERE IS_US_PORT=1 AND ID<>0 AND DELETED='N' AND IS_TMP='N'