-- REFERENCE DATA
SELECT PORT.CODE,UN.COUNTRY + UN.LOCATION AS 'UNLOCODE',PORT.ID
INTO TEMP_PES.DBO.PORT_REF_UPD
FROM GTCORE_MASTERDATA.DBO.REF_UNLOCODE_UNLOCODES UN WITH (NOLOCK)
JOIN GTCORE_MASTERDATA.DBO.REF_PORT PORT WITH (NOLOCK) ON UN.NAME = PORT.PORT_NAME
JOIN GTCORE_MASTERDATA.DBO.REF_COUNTRY COUNTRY WITH (NOLOCK) 
ON SUBSTRING(PORT.CODE, 1, 3) = COUNTRY.JOC_CODE
WHERE COUNTRY.[ISO ALPHA-2 CODE] = UN.COUNTRY

-- CHECK IF THE NAME_KEY ALREADY EXISTS IN THE TABLE
SELECT *
FROM TEMP_PES.DBO.PORT_REF_UPD
WHERE UNLOCODE IN (SELECT NAME_KEY FROM LIB_PORT (NOLOCK))


-- INSERT STATEMENTS
INSERT INTO LIB_PORT
SELECT  CODE,
	    UNLOCODE,
		ID,
		'Y' ACTIVE,
		GETDATE() MOD_DT,
		'DATA_DEV' MOD_BY,
		 CASE WHEN SUBSTRING(UNLOCODE,1,2) = 'US' THEN 1
         ELSE 0 END  AS USPORT 
 FROM TEMP_PES.DBO.PORT_REF_UPD

-- VERIFY THE INSERTED DATA
SELECT * FROM  LIB_PORT (NOLOCK)
WHERE MODIFY_USER = 'DATA_DEV'
AND SUBSTRING(NAME_KEY,1,2) = 'US'

-- CHECK IF THE COUNT OF THIS QUERY INCREASES AFTER UPDATE
SELECT ID,CODE,CAST(REPLACE(RTRIM(LTRIM(PIERS_NAME)),' ','') AS VARCHAR(35)) AS PIERS_NAME 
FROM REF_PORT 
WHERE IS_US_PORT=0 AND 
IS_TMP='N' AND 
DELETED='N' 
AND PIERS_NAME IN(SELECT LTRIM(RTRIM(PIERS_NAME)) FROM REF_PORT 
WHERE IS_US_PORT=0 AND 
IS_TMP='N' AND 
DELETED='N' 
GROUP BY PIERS_NAME HAVING COUNT(*)=1
) 

SELECT A.REF_ID,CAST(REPLACE(RTRIM(LTRIM(A.NAME_KEY)),' ','') AS VARCHAR(35)) AS NAME_KEY FROM LIB_PORT A  WITH (NOLOCK) ,  
REF_PORT B  WITH (NOLOCK)   
WHERE A.NAME_KEY IN(SELECT C.NAME_KEY FROM LIB_PORT C  WITH (NOLOCK)  JOIN REF_PORT D  WITH (NOLOCK)  ON C.REF_ID=D.ID WHERE C.IS_US_PORT=0   
AND D.IS_US_PORT=0 AND D.DELETED='N' GROUP BY C.NAME_KEY HAVING COUNT(*)=1) AND   
A.IS_US_PORT=0 AND   
A.REF_ID=B.ID AND   
B.DELETED='N' AND   
B.IS_TMP='N' AND   
B.IS_US_PORT=0  


  
  






