/*USE HMM
GO
DBCC SHRINKFILE(HMM_log, 1)
BACKUP LOG  HMM WITH TRUNCATE_ONLY
DBCC SHRINKFILE(HMM_log, 1)
GO

USE Evergreen
GO
DBCC SHRINKFILE(Evergreen_log, 1)
BACKUP LOG  Evergreen WITH TRUNCATE_ONLY
DBCC SHRINKFILE(Evergreen_log, 1)
GO


USE MSC
GO
DBCC SHRINKFILE(Msc_log, 1)
BACKUP LOG  MSC WITH TRUNCATE_ONLY
DBCC SHRINKFILE(Msc_log, 1)
GO

USE tempdb
GO
DBCC SHRINKFILE(templog, 1)
BACKUP log  tempdb WITH TRUNCATE_ONLY
DBCC SHRINKFILE(templog, 1)
GO


*/

Evergreen_log