-- RAW DATA

SELECT distinct NAME FROM REF_VESSEL (NOLOCK)
EXCEPT
SELECT distinct VESSEL FROM PES_REGISTRY_RULES (NOLOCK)

SELECT TOP 10  * FROM REF_CARRIER

SELECT * FROM PES_REGISTRY_RULES (NOLOCK) WHERE SLINE = TYPE



SELECT TOP 10 *
fROM  REF_CARRIER (NOLOCK)
 

SELECT TOP 10 * 
FROM PES_REGISTRY_RULES (NOLOCK)



SELECT *
FROM PES_REGISTRY_RULES (NOLOCK)
JOIN REF_CARRIER (NOLOCK)
ON SLINE = TYPE
WHERE DELETED = 'N'

SELECT DIR, VESSEL, CODE, REGISTRY
FROM PES_REGISTRY_RULES
JOIN REF_CARRIER
ON SLINE = TYPE
WHERE DELETED = 'N'
AND VESSEL = 'ZIM CONSTANZA'




SELECT VESSEL_COUNTRY,VESSEL_NAME,* FROM ARCHIVE_RAW_BOL (NOLOCK)
 WHERE BOL_ID IN (254867540,253584615,253121267,255790813)

VESSEL_COUNTRY	VESSEL_NAME
DE	ITAL CONTESSA
PA	JINHE
SG	APL JADE
IL	ZIM CONSTANZA

-- STAGING
SELECT BOL_ID,VESSEL_REF_ID,VESSEL_NAME,SRC_VESSEL_NAME,* FROM PES_STG_BOL (NOLOCK)
WHERE BOL_ID IN (254867540,253584615,253121267,255790813)

BOL_ID	VESSEL_REF_ID	VESSEL_NAME	SRC_VESSEL_NAME
253121267	9244	ITAL CONTESSA                      	ITAL CONTESSA
253584615	9244	JIN HE                             	JINHE
254867540	9244	APL JADE                           	APL JADE
255790813	9244	ZIM CONSTANZA                      	ZIM CONSTANZA

-- FROM RAW TO STAGING

-- VESSEL_COUNTRY = GERMANY
SELECT * FROM REF_COUNTRY WHERE [ISO ALPHA-2 CODE] IN ('DE','PA','SG','IL')
GERMANY
ISRAEL
PANAMA
SINGAPORE

-- LOOK UP VESSEL AND COUNTRY MATCH 
SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME = '' 
AND LKP_STND_VESSEL_COUNTRY = ''

O/P: FLKP_VESSEL_NAME_CNTRY_ID - ID
     FZY_NAME - STND_VESSEL

-- MATCH FOUND
SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME = 'ITALCONTESSA' 
AND LKP_STND_VESSEL_COUNTRY = 'GERMANY'
FZY_NAME = 'ITAL CONTESSA'  FLKP_VESSEL_NAME_CNTRY_ID = 236831

Select Country From Dbo.REF_Country (nolock)  where Country='AZERBAIJAN'
except
SELECT LKP_STND_VESSEL_COUNTRY FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK) where LKP_STND_VESSEL_COUNTRY='LKP_STND_VESSEL_COUNTRY'



SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME = '' 
AND LKP_STND_VESSEL_COUNTRY = ''

SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE LKP_STND_VESSEL IN ('JINHE','APLJADE' )

-- NO MATCH - INVALID
SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME = 'JINHE' 
AND LKP_STND_VESSEL_COUNTRY = 'PANAMA'
FZY_NAME = ''  FLKP_VESSEL_NAME_CNTRY_ID = ''

-- NO MATCH - INVALID
SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME = 'APLJADE' 
AND LKP_STND_VESSEL_COUNTRY = 'SINGAPORE'
FZY_NAME = ''  FLKP_VESSEL_NAME_CNTRY_ID = ''

-- MATCH FOUND
SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME = 'ZIMCONSTANZA' 
AND LKP_STND_VESSEL_COUNTRY = 'ISRAEL'

FZY_NAME = 'ZIM CONSTANZA'  FLKP_VESSEL_NAME_CNTRY_ID = 400712

-- COMPRESSED VESSEL NAME
SELECT REPLACE(LTRIM(RTRIM(VESSEL_NAME)),' ','') AS COMP_VESSEL_NAME
FROM ARCHIVE_RAW_BOL (NOLOCK)
WHERE BOL_ID IN (254867540,253584615,253121267,255790813)

-- COUNTRIES FOR THESE VESSELS FROM PES_REF_LIB_VESSEL_NAME_COUNTRY TABLE
SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE LKP_STND_VESSEL_NAME IN ('ITALCONTESSA','JINHE','APLJADE','ZIMCONSTANZA' )

SINGAPR
CHINAP
GERMANY
ISRAEL

-- LOOK UP 2 FOR INVALID VESSELS
-- FZY_NAME = ''
O/P: 
FZY_VESSEL_ID = 85630  'APLJADE'                
FZY_VESSEL_ID = 204683 'JINHE'

SELECT ID,STND_VESSEL,* FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE LKP_STND_VESSEL IN ('JINHE','APLJADE' )

-- RELOOK UP VESSEL MATCH ON ID'S

SELECT STND_VESSEL,IMO_CODE FROM REF_VESSEL (NOLOCK)
WHERE ID IN (85630,204683)

(!ISNULL(RELKP_VESSEL_NAME) && LTRIM(RELKP_VESSEL_NAME) != '') ? RELKP_VESSEL_NAME : VESSEL_NAME








