  
CREATE PROCEDURE [dbo].[USP_PES_SHORT_DESC_STG_CMD_NORAWCMD]   
AS  
BEGIN  
  
-- [aa] - 11/28/2010  
-- Log start time  
DECLARE @IdLogOut int, @DbName varchar(100), @SprocName varchar(100), @ParametersIn varchar(MAX)  
SELECT @DbName = @@SERVERNAME + '; ' + DB_NAME(), @SprocName = OBJECT_NAME(@@PROCID)  
,@ParametersIn = NULL  
EXEC SCREEN_TEST.dbo.usp_LogSProcCallsStart  
 @DbName = @DbName ,@SprocName = @SprocName ,@Parameters = @ParametersIn ,@IdLog = @IdLogOut OUT  
  
  
DECLARE @TRANNAME VARCHAR(20),@FILE VARCHAR(500),@FILE_NAME VARCHAR(50)  
DECLARE @CMD VARCHAR(1000),@ERROR_MESSAGE VARCHAR(1000),  
@ERROR_NUMBER VARCHAR(50),@ERROR_LINE VARCHAR(50),@LOADNUM INT  
SET @TRANNAME = 'MYTRANSACTION'  
  
SELECT @FILE = PATH   
FROM PES.DBO.PES_CONFIGURATION  WITH (NOLOCK)   
WHERE SOURCE='SP_LOG'  
  
SELECT @FILE_NAME= FILENAME   
FROM PES.DBO.PES_PROGRESS_STATUS  WITH (NOLOCK)   
WHERE LOADNUMBER=(  
     SELECT TOP 1 LOAD_NUMBER   
     FROM PES.DBO.RAW_BOL  WITH (NOLOCK)   
     )  
  
SET @FILE='"'+@FILE+@FILE_NAME+'_LOG.TXT'+'"'  
  
BEGIN TRANSACTION @TRANNAME  
  
BEGIN TRY  
  
CREATE TABLE #TEMP_CMD   
(  
 BOL_ID NUMERIC(12,0),  
 BATCH_ID VARCHAR(10),  
 CMD_SEQ_NBR INT ,  
 ENH_DESC VARCHAR(100),  
 PIERS_PIECE_CNT NUMERIC(12,0),  
 PIERS_PIECE_UNIT VARCHAR(9), --needs to be updated using PPMM_PACK  
 HSCODE VARCHAR(10),  
 PIECE_UNIT_ID NUMERIC(12,0), --needs to be calculated  
 JOC_CD VARCHAR(10),  
 DIRECTION VARCHAR(1),  
 CONQTY INT,  
 CONFLAG CHAR(1),  
 CONVOL INT,  
 CONSIZE VARCHAR(2),  
 CONLENGTH VARCHAR(1), --needs to updated when calculated  
 CONWIDTH VARCHAR(1),  
 CONTYPE VARCHAR(2),  
 WGT NUMERIC(22,6),   
 LOAD_NBR NUMERIC(12,0)   
)  
  
  
  
INSERT INTO #TEMP_CMD(BOL_ID,BATCH_ID,CMD_SEQ_NBR,ENH_DESC,PIERS_PIECE_CNT,PIERS_PIECE_UNIT,HSCODE,JOC_CD,  
      CONQTY,CONFLAG,CONVOL,CONSIZE,WGT, LOAD_NBR)  
  
SELECT top 100 A.BOL_ID,C.BATCH_ID,1,'NO RAW COMMODITY',BOL_QTY,MANIFEST_UNIT,'007985','7985000',  
  ISNULL(CONQTY,0),ISNULL(CONFLAG,' '),ISNULL(CONVOL,0),ISNULL(CONSIZE,'  '),ISNULL(BOL_WGT,0) WEIGHT, LOAD_NUMBER  
FROM PES_STG_BOL  A WITH (NOLOCK)  
JOIN ARCHIVE_RAW_BOL C  
ON A.BOL_ID = C.BOL_ID  
LEFT JOIN ARCHIVE_RAW_CMD B  
ON A.BOL_ID = B.BOL_ID  
WHERE --B.BOL_ID IS NULL --AND (BOL_STATUS <> 'DELETE' OR RECORD_STATUS <> 'DELETE' OR BOL_NBR <> 'DELETE') 
--and 
A.BOL_ID in (
246183860,
246183889,
246400497,
246400500,
246400502,
246407518,
246407569,
246407570,
246407573,
246407589,
246407640,
246407705,
246407711,
246407712,
246571775,
246571779,
246571798,
246571803,
248035674
)






 

select * from pes_stg_cmd (nolock) where
bol_id in (
224749966,
224749967,
224749979,
224750011,
224750139,
224750140,
224750177)

select top 10 * from PES.DBO.PES_PPMM_PACK
where id = 87


select * from pes_stg_cmd (nolock) where
cmd_id in (
138271690,
138283369,
138283367,
138283368,
138598085,
138598084,
138487792
)
--select * from #temp_cmd  
  
UPDATE C SET PIERS_PIECE_UNIT = UM,PIECE_UNIT_ID =ID  
FROM #TEMP_CMD C   
JOIN PES.DBO.PES_PPMM_PACK P  WITH (NOLOCK)    
ON P.AMSUM=LTRIM(RTRIM(C.PIERS_PIECE_UNIT))   
WHERE ISNULL(LTRIM(RTRIM(PIERS_PIECE_UNIT)),'') <> ''   
  
--UPDATE CONLENGTH, CONTYPE AND CONWIDTH  
UPDATE B  
SET  CONLENGTH= CASE WHEN ISNULL(LTRIM(RTRIM(A.CONTAINER_TYPE)),'')=''   
     THEN 'N' ELSE SUBSTRING(A.CONTAINER_TYPE,1,1) END,  
  CONWIDTH= CASE WHEN ISNULL(LTRIM(RTRIM(A.CONTAINER_TYPE)),'')=''   
     THEN 'U' ELSE SUBSTRING(A.CONTAINER_TYPE,2,1) END,   
  CONTYPE= CASE WHEN ISNULL(LTRIM(RTRIM(A.CONTAINER_TYPE)),'')=''   
     THEN 'LL' ELSE SUBSTRING(A.CONTAINER_TYPE,3,2) END  
FROM #TEMP_CMD  B  
JOIN ARCHIVE_RAW_CNTR A  WITH (NOLOCK)     
ON A.BOL_ID = B.BOL_ID   
WHERE BATCH_ID = 'AMS'  
  
UPDATE #TEMP_CMD SET PIERS_PIECE_UNIT = 'BLS',PIECE_UNIT_ID = ID  
FROM   
(  
SELECT BOL_ID,CMD_SEQ_NBR   
FROM  #TEMP_CMD  
WHERE PIERS_PIECE_UNIT = 'BLC'  
)A  
JOIN #TEMP_CMD B  
ON A.BOL_ID = B.BOL_ID AND A.CMD_SEQ_NBR = B.CMD_SEQ_NBR   
JOIN PES_PPMM_PACK  
ON UM = 'BLS'  
  
UPDATE #TEMP_CMD SET PIECE_UNIT_ID=0, PIERS_PIECE_UNIT = ''  
WHERE PIECE_UNIT_ID IS NULL   
  
UPDATE PES.DBO.PES_STG_BOL WITH(UPDLOCK) SET QC_VALID='N'   
WHERE BOL_ID IN (SELECT BOL_ID FROM #TEMP_CMD)  
  
INSERT INTO PES.DBO.TEMP_PES_STG_CMD_SHORT_DESC (BOL_ID,CMD_HSCODE,CMD_CD,JOC_CODE,CMD_SEQ_NBR,CMD_DESC,CMD_WGT_VALUE,CMD_VALUE_VALUE,  
        CMD_PIECE_CNT,REF_PIECE_UNIT_ID,PIECE_UNIT,CMD_TEU,RECORD_STATUS,CMD_FCHARGE,LOADNUMBER,  
        CNTR_QUANTITY,CNTR_VOL,CNTR_SIZE,CNTR_FLAG,CON_LENGTH,CON_WIDTH,CON_TYPE)  
      
SELECT BOL_ID,HSCODE,JOC_CD AS CMD_CD,JOC_CD,CMD_SEQ_NBR,REPLACE(ENH_DESC,' AND ', ' & ') ENH_DESC,ISNULL(WGT,0) WEIGHT,0,  
  PIERS_PIECE_CNT,PIECE_UNIT_ID,PIERS_PIECE_UNIT,0,'PENDING',0,LOAD_NBR,  
  CONQTY,CONVOL,CONSIZE,CONFLAG,CONLENGTH,CONWIDTH,CONTYPE  
FROM #TEMP_CMD  
  

SELECT * FROM REF_MEASURE WHERE ID IN (6,42,129)
-----------------------------------------------------------------------------------------------------------------------------------  
 --DROP TEMPORARY TABLES  
 --DROP TABLE #TEMP_CMD  
 --DROP TABLE @TEMP_BL_CMDS  
COMMIT TRANSACTION @TRANNAME  
  
END TRY  
  
BEGIN CATCH  
 SET @ERROR_NUMBER=ERROR_NUMBER()  
 SET @ERROR_LINE=ERROR_LINE()  
 SET @ERROR_MESSAGE='STORED PROCEDURE USP_PES_SHORT_DESC_STG_CMD FAILED WITH  AT LINE NUMBER:  ' + @ERROR_LINE + ' WITH ERROR DESCRIPTION:  '+ERROR_MESSAGE()  
   
 SET @CMD = 'ECHO ERROR_MESSAGE-- '+@ERROR_MESSAGE+ ' >> '+ @FILE  
 EXEC MASTER..XP_CMDSHELL @CMD   
    SET @CMD = 'ECHO ERROR_NUMBER-- '+@ERROR_NUMBER+ ' >> '+ @FILE  
 EXEC MASTER..XP_CMDSHELL @CMD   
 SET @CMD = 'ECHO ERROR_LINE-- '+@ERROR_LINE+ ' >> '+ @FILE  
 EXEC MASTER..XP_CMDSHELL @CMD   
   
 --DROP TEMPORARY TABLES  
 --DROP TABLE @TEMPSHTCOUNT  
 --DROP TABLE @TEMP_BL_CMDS  
   
   
 SET @CMD = 'ECHO TRANSACTIONS ROLLBACKED'+ ' >> '+ @FILE  
 EXEC MASTER..XP_CMDSHELL @CMD   
 RAISERROR(@ERROR_MESSAGE,21,1) WITH LOG  
  
 ROLLBACK TRANSACTION @TRANNAME  
END CATCH  
  
  
-- [aa] - 11/28/2010  
-- Log end time  
EXEC SCREEN_TEST.dbo.usp_LogSProcCallsEnd  
 @Id = @IdLogOut ,@RowsAffected = @@ROWCOUNT  
  
END  


sp_helptext PES_SP_RULES
  
  
  

select * from PES.DBO.TEMP_PES_STG_CMD_SHORT_DESC (nolock)
where bol_id in
(
246183860,
246183889,
246400497,
246400500,
246400502,
246407518,
246407569,
246407570,
246407573,
246407589,
246407640,
246407705,
246407711,
246407712,
246571775,
246571779,
246571798,
246571803,
248035674)
