

 -- GET THE COMMODITIES WHICH ARE CARS

-- 45584

SELECT DISTINCT CMD.BOL_ID 

INTO TEMP_PES.DBO.CARS_UNITS

FROM PES_STG_VIN VIN (NOLOCK) JOIN PES_STG_CMD CMD (NOLOCK)

ON VIN.T_NBR = CMD.BOL_ID

AND CMD.REF_PIECE_UNIT_ID <> 129

AND CMD.JOC_CODE = '6921000'

-- 45584

SELECT COUNT(*)

FROM TEMP_PES.DBO.CARS_UNITS CARS (NOLOCK)

-- RECORDS TO BE UPDATED ON STAGING

-- 50559

SELECT MONTH(VDATE) AS MONTH,YEAR(VDATE) AS YEAR,COUNT(*)

FROM PES_STG_CMD CMD (NOLOCK),TEMP_PES.DBO.CARS_UNITS CARS (NOLOCK)

WHERE CMD.BOL_ID = CARS.BOL_ID

-- AND CMD.REF_PIECE_UNIT_ID <> 129

AND CMD.JOC_CODE = '6921000'
GROUP BY MONTH(VDATE),YEAR(VDATE) 

SELECT  TOP 10 * FROM PES_STG_CMD  (NOLOCK) 

SELECT DISTINCT JOC_CODE FROM PES_STG_CMD  (NOLOCK)  WHERE JOC_CODE LIKE '%6921%'

-- REF TABLE on 132 

-- 129 = 'UNT'

SELECT * FROM dbo.REF_MEASURE(NOLOCK) WHERE ID = 129

SELECT STG.* 
INTO TEMP_PES.DBO.CARS_UNITS_2010
FROM PES_STG_BOL STG(NOLOCK),TEMP_PES.DBO.CARS_UNITS CARS (NOLOCK)
WHERE STG.BOL_ID = CARS.BOL_ID
AND YEAR(VDATE) = '2010'

SELECT  COUNT(*) FROM TEMP_PES.DBO.CARS_UNITS_2011

SELECT  top 10 * FROM TEMP_PES.DBO.CARS_UNITS_2011

BEGIN TRAN
-- 2012 -- 16707 records affected
-- 2011 -- 23229 records affected
UPDATE CMD
SET CMD.REF_PIECE_UNIT_ID = 129,MODIFY_DATE = GETDATE(),MODIFY_USER = 'DATA_DEV'
FROM PES_STG_CMD CMD (NOLOCK),TEMP_PES.DBO.CARS_UNITS_2010 CARS (NOLOCK)
WHERE CMD.BOL_ID = CARS.BOL_ID
--AND CMD.REF_PIECE_UNIT_ID <> 129
AND CMD.JOC_CODE = '6921000'
AND ISNULL(IS_DELETED,'') <> 'Y'

UPDATE PES_STG_BOL SET MODIFY_DATE = GETDATE(),MODIFY_USER = 'DATA_DEV'
WHERE BOL_ID IN (SELECT BOL_ID FROM TEMP_PES.DBO.CARS_UNITS_2010 (NOLOCK))

commit TRAN

SELECT * FROM REF_MEASURE (NOLOCK) WHERE UNIT = 'UNT'







