-- Data descrepancy between PES_REF_LIB_VESSEL_NAME and REF_VESSEL
-- 8683 rows 

SELECT * INTO TEMP_PES.DBO.VESSEL_REF_DATA FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE STND_VESSEL IN (
SELECT ID,STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
EXCEPT
SELECT ID,STND_VESSEL FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N')

SELECT * FROM TEMP_PES.DBO.VESSEL_REF_DATA


-- 47263
SELECT COUNT(DISTINCT STND_VESSEL) FROM PES_REF_LIB_VESSEL_NAME V (NOLOCK)

-- 47263
SELECT COUNT(DISTINCT STND_VESSEL) FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)

SELECT * FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE STND_VESSEL = 'MVALESSANDRADAMATO'

SELECT * FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE STND_VESSEL = 'ALESSANDRA D AMAT'

SELECT * FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)
WHERE ID = 58

SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE ID = 58

SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE STND_VESSEL = 'ALESSANDRA D AMAT'

SELECT * FROM REF_VESSEL (NOLOCK)
WHERE ID = 58
 

-- MATCHING VESSEL LOOK UP DATA BASED ON VESSEL ID
-- 49577 ROWS
SELECT V.ID AS VID,R.ID AS RID,V.STND_VESSEL AS VNAME,R.NAME AS RNAME,R.DELETED 
INTO TEMP_PES.DBO.MATCH_VESSEL_DATA
FROM PES_REF_LIB_VESSEL_NAME V (NOLOCK) JOIN REF_VESSEL R (NOLOCK)
  ON V.ID = R.ID 


-- MATCHING VESSELS BASED ON ID AND VESSEL NAME
-- 40881 ROWS 
SELECT V.ID AS VID,R.ID AS RID,V.STND_VESSEL AS VNAME,R.NAME AS RNAME,R.DELETED 
FROM PES_REF_LIB_VESSEL_NAME V (NOLOCK) JOIN REF_VESSEL R (NOLOCK)
  ON V.ID = R.ID AND V.STND_VESSEL = R.STND_VESSEL


-- NON MATCHING VESSEL LOOK UP DATA 
-- 8699 ROWS
SELECT V.ID AS VID,R.ID AS RID,V.STND_VESSEL AS VNAME,R.NAME AS RNAME,R.DELETED 
  INTO TEMP_PES.DBO.NONMATCH_VESSEL_DATA
FROM PES_REF_LIB_VESSEL_NAME V (NOLOCK) JOIN REF_VESSEL R (NOLOCK)
  ON V.ID = R.ID AND V.STND_VESSEL <> R.STND_VESSEL

-- CHECK IF ANY OF THESE VESSELS IN REF_VESSEL ARE MISSING IN THE LOOK UP TABLE PES_REF_LIB_VESSEL_NAME 
SELECT RID,RNAME FROM TEMP_PES.DBO.NONMATCH_VESSEL_DATA
EXCEPT
SELECT ID,STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)

SELECT * FROM TEMP_PES.DBO.NONMATCH_VESSEL_DATA

-- 4909 ROWS
SELECT ID,COUNT(ID) 
FROM PES_REF_LIB_VESSEL_NAME
WHERE ID IN (SELECT RID FROM  TEMP_PES.DBO.NONMATCH_VESSEL_DATA)
GROUP BY ID
HAVING COUNT(ID) >1

SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE STND_VESSEL = 'AFRICAN FERN'

SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK) WHERE ID =  19
SELECT * FROM REF_VESSEL (NOLOCK) WHERE ID = 19

-- CHECK IF THE REFVESSEL VESSEL NAME AND ID EXISTS IN PES_REF_LIB_VESSEL_NAME
-- 5065 ROWS
SELECT RNAME FROM TEMP_PES.DBO.NONMATCH_VESSEL_DATA
WHERE RNAME NOT IN (SELECT STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK))

SELECT * FROM SCREEN_TEST.DBO.CTRL_QC_MODIFY (NOLOCK)
WHERE [KEY] LIKE '%COMP%'

SELECT TOP 10 * FROM SCREEN_TEST.DBO.CTRL_PROCESS_VOYAGE (NOLOCK)
WHERE PROCESS_NAME LIKE '%COMPANY%'


SELECT TOP 10 * FROM dbo.PES_TRANSACTIONS_LIB_PTY (NOLOCK)
WHERE COMP_ID IS NULL

SELECT ROUTINE_NAME, ROUTINE_DEFINITION 
    FROM INFORMATION_SCHEMA.ROUTINES 
    WHERE ROUTINE_DEFINITION LIKE '%PES_REGISTRY%' 
    AND ROUTINE_TYPE='PROCEDURE' 






















SELECT * FROM TEMP_PES.DBO.NONMATCH_VESSEL_DATA


-- NON MATCHING VESSEL LOOK UP DATA BASED ON VESSEL ID

SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
WHERE ID NOT IN (SELECT ID FROM REF_VESSEL (NOLOCK) WHERE DELETED  = 'N')


SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK) where stnd_vessel = 'CARRIBEAN HWY'
SELECT * FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N' and stnd_vessel = 'CARRIBEAN HWY'

SELECT * FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N'

SELECT STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
except
SELECT STND_VESSEL FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N'

