select top 10 * from pes_progress_status (nolock) 
order by load_dt desc

12235001
12234001

SELECT * INTO TEMP_PES.DBO.PES_STG_BOL_AUG29 FROM PES_STG_BOL (NOLOCK)
WHERE REF_LOAD_NUM_ID IN (12235001,12234001)

SELECT * FROM PES_STG_BOL (NOLOCK)
WHERE REF_LOAD_NUM_ID IN (12235001,12234001)
AND VESSEL_REF_ID IN (9244,6844)

DROP TABLE TEMP_PES.DBO.DQA_VOYAGE_AUG29 

-- TOTAL CNT = 692161 NOT CHANGING
--3061 -- 3066 -- 3077
-- UPDATE RUNNING
SELECT *  FROM SCREEN_TEST.DBO.DQA_VOYAGE (NOLOCK)
WHERE --MODIFIED_DT > (GETDATE() - 1)
--AND 
VESSEL_ID = 6844
ORDER BY MODIFIED_DT DESC



Select * from  GTCore_MasterData.dbo.ref_vessel where  name='HANJIN LONDON'
 SELECT top 10 *  FROM SCREEN_TEST.DBO.DQA_VOYAGE (NOLOCK) WHERE VESSEL_Name = 'CMA CGM VIVALDI'

Select * from CMA CGM VIVALDI                    9244
Select top 10 * from PES.DBO.REF_VESSEL (nolock)
SELECT COUNT(*) FROM SCREEN_TEST.DBO.DQA_VOYAGE (NOLOCK)
WHERE MODIFIED_DT > (GETDATE() - 1)
AND VESSEL_ID = 9244
--ORDER BY MODIFIED_DT DESC

SELECT COUNT(*) FROM SCREEN_TEST.DBO.BL_BL (NOLOCK)
WHERE LAST_UPDATE_DT > (GETDATE() - 1)

SELECT * INTO TEMP_PES.DBO.DQA_VOYAGE_AUG29_1 FROM SCREEN_TEST.DBO.DQA_VOYAGE (NOLOCK)
WHERE MODIFIED_DT > (GETDATE() - 1)

SELECT * FROM TEMP_PES.DBO.DQA_VOYAGE_AUG29_1 
WHERE VESSEL_ID = 9244
ORDER BY MODIFIED_DT DESC

SELECT sqltext.TEXT,
req.session_id,
req.status,
req.command,
req.cpu_time,
req.total_elapsed_time
FROM sys.dm_exec_requests req
CROSS APPLY sys.dm_exec_sql_text(sql_handle) AS sqltext 

SP_HELPTEXT  PES_LOAD_LIB_TRANSACTIONS_INTO_STG_PTY


-- PES_LOAD_LIB_TRANSACTIONS_INTO_STG_PTY
-- PES.dbo.PES_SP_CALL_SSIS_RAW_STAGING_PACKAGE;1










