-- 49562
SELECT COUNT(*) FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)

-- 0 rows
SELECT id,STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK) where id  = 72437
EXCEPT 
SELECT id,STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK) where stnd_vessel like '%QH7%'

-- 49562
SELECT COUNT(*) FROM PES_REF_LIB_VESSEL_NAME_COUNTRY (NOLOCK)


-- Data descrepancy between PES_REF_LIB_VESSEL_NAME and REF_VESSEL
-- 8683 rows 

SELECT * FROM PES_REF_LIB_VESSEL_NAME (NOLOCK) where stnd_vessel like '%QH7%'
WHERE STND_VESSEL IN (
SELECT STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)
EXCEPT
SELECT STND_VESSEL FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N')

-- 0 rows
SELECT STND_VESSEL FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N'
EXCEPT
SELECT STND_VESSEL FROM PES_REF_LIB_VESSEL_NAME (NOLOCK)

-- 8645 rows
SELECT COUNT(*) FROM LIB_VESSEL (NOLOCK)

SELECT REF_NAME FROM LIB_VESSEL (NOLOCK) 
EXCEPT
SELECT STND_VESSEL FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N'

-- 77350 rows
SELECT COUNT(*) FROM PES_PROD_REF_VESSEL (NOLOCK)

-- 33649 rows
SELECT COUNT(*) FROM REF_VESSEL_PES (NOLOCK)

-- 67828 ROWS
SELECT COUNT(*) FROM GTCore_MasterData.DBO.REF_IMO_VESSEL (NOLOCK)


-- 23560 ROWS
SELECT NAME FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N'
EXCEPT
SELECT SHIPNAME FROM GTCore_MasterData.DBO.REF_IMO_VESSEL (NOLOCK) 

-- 47165 ROWS
SELECT SHIPNAME FROM GTCore_MasterData.DBO.REF_IMO_VESSEL (NOLOCK) 
EXCEPT
SELECT NAME FROM REF_VESSEL (NOLOCK) WHERE DELETED = 'N'

-- 33649 ROWS
SELECT COUNT(*) FROM REF_VESSEL_PES (NOLOCK)

select * from PES_REGISTRY_RULES

