-- GET THE COMMODITIES WHICH ARE CARS
-- 45584
SELECT DISTINCT CMD.BOL_ID 
INTO TEMP_PES.DBO.CARS_UNITS
FROM PES_STG_VIN VIN (NOLOCK) JOIN PES_STG_CMD CMD (NOLOCK)
ON VIN.T_NBR = CMD.BOL_ID
AND CMD.REF_PIECE_UNIT_ID <> 129
AND CMD.JOC_CODE = '6921000'

-- 45584
SELECT COUNT(*)
FROM TEMP_PES.DBO.CARS_UNITS CARS (NOLOCK)

-- RECORDS TO BE UPDATED ON STAGING
-- 50559
SELECT CMD.*
FROM PES_STG_CMD CMD (NOLOCK),TEMP_PES.DBO.CARS_UNITS CARS (NOLOCK)
WHERE CMD.BOL_ID = CARS.BOL_ID
  AND CMD.REF_PIECE_UNIT_ID <> 129
  AND CMD.JOC_CODE = '6921000'

-- REF TABLE on 132
SELECT * FROM dbo.REF_MEASURE(NOLOCK) WHERE ID = 129

-- UPDATE
UPDATE PES_STG_CMD
SET CMD.REF_PIECE_UNIT_ID = 129,MODIFY_DATE = GETDATE()
FROM PES_STG_CMD CMD (NOLOCK),TEMP_PES.DBO.CARS_UNITS CARS (NOLOCK)
WHERE CMD.BOL_ID = CARS.BOL_ID
  AND CMD.REF_PIECE_UNIT_ID <> 129
  AND CMD.JOC_CODE = '6921000'











